version: "3"
services:
    django:
        restart: always
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: django
        volumes:
            - /home/data/DjangoTodo/upload:/app/django_todo/upload
            - /home/data/DjangoTodo/log:/app/log
        depends_on:
            - mysql
        networks: 
            - network
        environment:
            TZ: Asia/Shanghai # 设置容器时区
            PROJECT_ENV: prod
        ports:
            - 7009:7009
        env_file:
            - ./env/.prod.env
        command: /start

    mysql:
        restart: always
        image: mysql:5.7.26
        container_name: mysql
        command: --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci # 设置utf8字符集
        environment:
            TZ: Asia/Shanghai # 设置容器时区
            MYSQL_ROOT_PASSWORD: oceanover
        networks: 
            - network
        ports:
            - 3306:3306
        volumes:
            - /home/data/mysql/data:/var/lib/mysql # 映射数据库保存目录到宿主机，防止数据丢失

    nginx:
        restart: always
        image: nginx
        container_name: nginx
        networks: 
            - network
        depends_on:
            - django
        ports:
            - 80:80
        volumes:
            - ./nginx/conf:/etc/nginx/conf.d
            - /home/data/web:/web
            - /home/data/DjangoTodo/upload:/upload

networks:
    network:
        driver: bridge
